### ISSUE TITLE
__autoload() function deprecated error is occurring 

### ISSUE THREAD

**Issue by vbadkar** [Libbna/BLOG_SITE#11]
After loading the site a deprecated error is observed for __autoload() function, although the content gets loaded without the css
Attaching screenshots of the same.
![image](https://user-images.githubusercontent.com/87715018/132120277-e0eebbf2-7d11-48de-85aa-e97d52e63b5e.png)
![image](https://user-images.githubusercontent.com/87715018/132120285-90792751-96fa-4420-af7e-6126d5f0562c.png)

**Comment by vbadkar** [comment]
After changing the code to this:-
![image](https://user-images.githubusercontent.com/87715018/132121131-9c413659-ce0b-4a00-873f-16967bcca023.png)
The error is not occurring anymore but the CSS unable to load issue is still occurring, will create a new issue for it closing this issue as it doesn't seems to be related to the CSS.

**Comment by Libbna** [comment]
spl_autoload_register() method is supported by the php versions (PHP 5 >= 5.1.0, PHP 7, PHP 8). 
I'm using PHP 7 and **changed the _autoload() method to spl_autoload_register()** method, it is working fine. 

![image](https://user-images.githubusercontent.com/46792570/132578466-621ef70e-d423-4ede-81bb-856720366dd6.png)
