### ISSUE TITLE
Remove the mysql credentials from the code and move it to a file which is gitignored.

### ISSUE THREAD

**Issue by JayKandari** [Libbna/BLOG_SITE#3]

**Comment by Libbna** [comment]
Tried to remove the MySQL credentials from the code and move to in a separate file and save it is a .gitignore file but it is still showing in file structure,. 
![Capture1](https://user-images.githubusercontent.com/46792570/130661269-6e8025d4-013d-4368-ac58-f3a4aa76d9bd.PNG)

**Comment by JayKandari** [comment]
@Libbna : can you remove the actual `includes/db.php` file from your repository. and then see if this works.

**Comment by Libbna** [comment]
@JayKandari I have removed the actual file from repository using the **git rm -r --cached includes** command.  Includes is a folder that contains two files config.php, and db.php. 
db.php was the file that I want to remove so I restored the other file which is config.php using **git restore --staged includes/config.php** and then commit the changes and pushed the code.

**Comment by JayKandari** [comment]
Verified this file `includes/db.php` is no longer present in the repo. Closing this.
